name: FactionsPro
author: MangoTheDev
description: Faction Plugin'
version: 1.4
main: FactionsPro\FactionMain
api: 3.0.0-ALPHA11
softdepend:
    - PureChat
    - AntiSpamPro
commands:
    f: { description: 'use /f help for all faction commands!', permission: f.command }
permissions:
    f.command: { default: true, description: 'Allow use of all faction commands' }
